import 'package:floor/floor.dart';
import 'package:todoapp/entities/owner.dart';
import 'package:todoapp/entities/pet.dart';
import 'package:todoapp/pet_doa/pet_dao.dart';

/*
The part directive indicates that `pet_database.g.dart` is 
a part of the same library. This file is generated by the Floor Generator
and contains code that complements the manually written code in pet_database.dart
allowing for a clean separation between generated and manually written code.
*/
part 'pet_database.g.dart';

// Define the database
@Database(
  version: 2,
  entities: [Owner, Pet],
  views: [PetOwner],
)

abstract class PetDatabase extends FloorDatabase {
  PetDao get petDao;
  OwnerDao get ownerDao;
}
